server:
  context-path: /springboot
  jsp-servlet:
    init-parameters:
      development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      charset: UTF-8
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  profiles:
    active: test
